# Generated by Django 3.1.3 on 2020-12-03 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('id_service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagerecord',
            old_name='file',
            new_name='image_file',
        ),
        migrations.RemoveField(
            model_name='animalrecord',
            name='name',
        ),
    ]
