# Generated by Django 3.1.3 on 2020-12-09 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id_service', '0002_auto_20201203_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerecord',
            name='v0',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='imagerecord',
            name='v1',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='imagerecord',
            name='v2',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='imagerecord',
            name='v3',
            field=models.FloatField(null=True),
        ),
    ]
